# Generated by Django 3.2.6 on 2021-09-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_insta', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('deadline', models.DateTimeField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('icon_url', models.ImageField(blank=True, null=True, upload_to='pages/pictures/')),
                ('category', models.CharField(blank=True, max_length=250)),
                ('sub_category', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'pages',
            },
        ),
    ]
