# Generated by Django 3.2.6 on 2021-09-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageAD', '0002_favoritepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
