# Generated by Django 3.2.6 on 2021-09-21 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageAD', '0003_alter_pagead_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAdRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(choices=[('w', 'WEEK'), ('m', 'MONTH'), ('y', 'YEAR')], max_length=10)),
                ('page_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageAD.pagead')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
    ]
