# Generated by Django 3.2.6 on 2021-09-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageAD', '0004_pageadrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageadrequest',
            name='user',
        ),
    ]
