# Generated by Django 3.2.6 on 2021-09-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageAD', '0004_pageadrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritepage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pageAD.pagead'),
        ),
    ]
