# Generated by Django 3.2.6 on 2021-09-29 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageAD', '0005_remove_pageadrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagead',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagead',
            name='username_insta',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
