# Generated by Django 3.2.6 on 2021-10-24 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageAD', '0008_subcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritepage',
            unique_together={('user', 'page')},
        ),
    ]
